Repository xp-forge/web, pull requests merged in 2021-09, with the labels that each got.

#85 Fixed param value is urlencoded when doing multipart requests vie SAPI
  src/main/php/xp/web/SAPI.class.php
  src/test/php/web/unittest/server/SAPITest.class.php
Labels: bug

#86 Drop support for XP < 9
  composer.json
Labels: bc break

#87 Default server profile to "prod"
  src/main/php/xp/web/Runner.class.php
  src/main/php/xp/web/srv/Develop.class.php
  src/main/php/xp/web/srv/Standalone.class.php
Labels: enhancement
